import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Humain({ setSelectedOrgan, ...props }) {
  const { nodes, materials } = useGLTF('/humain.gltf');

  const handleClick = (organName) => {
    setSelectedOrgan(organName);
  };

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.male_zbrush_male_zbrush_0.geometry}
          material={materials.male_zbrush}  onClick={() => handleClick("morceau_de_peau")}
          
        />
        <mesh
          geometry={nodes.male_zbrush_male_zbrush_0_1.geometry}
          material={materials.male_zbrush}
          onClick={() => handleClick("reins")}
        />
        <mesh
          geometry={nodes.male_zbrush_male_zbrush_0_2.geometry}
          material={materials.male_zbrush}  onClick={() => handleClick("morceau_de_peau")}
          
        />
        <mesh geometry={nodes.male_zbrush_male_zbrush_0_3.geometry} material={materials.male_zbrush}  />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_4.geometry} material={materials.male_zbrush} onClick={() => handleClick("système_lymphatique")} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_5.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_6.geometry} material={materials.male_zbrush}  onClick={() => handleClick("système_lymphatique")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_7.geometry} material={materials.male_zbrush}  onClick={() => handleClick("poumons")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_8.geometry} material={materials.male_zbrush}  onClick={() => handleClick("coeur")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_9.geometry} material={materials.male_zbrush} onClick={() => handleClick("les_poumons")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_10.geometry} material={materials.male_zbrush}  onClick={() => handleClick("système_lymphatique")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_11.geometry} material={materials.male_zbrush}  onClick={() => handleClick("système_immunitaire")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_12.geometry} material={materials.male_zbrush}  />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_13.geometry} material={materials.male_zbrush} onClick={() => handleClick("système_immunitaire")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_14.geometry} material={materials.male_zbrush}  onClick={() => handleClick("morceau_de_peau")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_15.geometry} material={materials.male_zbrush}  onClick={() => handleClick("morceau_de_peau")}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_16.geometry} material={materials.male_zbrush}   onClick={() => handleClick("morceau_de_peau")}/>
        {/* Répétez pour chaque organe en associant une clé unique */}
      </group>
    </group>
  );
}

useGLTF.preload('/humain.gltf');





/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\humain.gltf 
Author: HEPL3D (https://sketchfab.com/HEPL3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tecg-284-dupont-william-anatomy-89661fe642014ded89da3edbcbe7e253
Title: TECG_284_Dupont_william_Anatomy
*/

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model(props) {
//   const { nodes, materials } = useGLTF('/humain.gltf')
//   const handleClick = () => {
//     alert("head ")

//   }
//   return (
//     <group {...props} dispose={null}>
//       <group scale={0.01}>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0.geometry} material={materials.male_zbrush} onClick={handleClick}/>
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_1.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_2.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_3.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_4.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_5.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_6.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_7.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_8.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_9.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_10.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_11.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_12.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_13.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_14.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_15.geometry} material={materials.male_zbrush} />
//         <mesh geometry={nodes.male_zbrush_male_zbrush_0_16.geometry} material={materials.male_zbrush}  />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/humain.gltf')
